# ASSIGNMENT 3

# Questions 1:

In [2]:
import numpy as np
array = np.arange(2,50,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:

In [3]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

12
76
45
6
43
34
55
32
26
76
[ 6 12 26 32 34 43 45 55 76 76]


# Questions 3:

In [7]:
arr=np.array([31,42,38,94,15,63])
print("the size of the array is",arr.size)
print("the dimension of the array is",arr.ndim)

the size of the array is 6
the dimension of the array is 1


# Questions 4:

In [10]:
arr_1d = np.array([10,31,52,93,14,55,6,47,28,99])
print("1d array\n",arr_1d)
arr_2d = np.reshape(arr_1d,(5,2))
print("2d array\n",arr_2d)

1d array
 [10 31 52 93 14 55  6 47 28 99]
2d array
 [[10 31]
 [52 93]
 [14 55]
 [ 6 47]
 [28 99]]


# Questions 5:

In [16]:
x = np.array([[11,22],[33,44]]) 
y = np.array([[55,66],[77,88]])
print("Vertical stacking:\n", np.vstack((x,y)))             # vertical stacking
print("horizantal stacking:\n",np.hstack((x,y)))              # horizontal stacking



Vertical stacking:
 [[11 22]
 [33 44]
 [55 66]
 [77 88]]
horizantal stacking:
 [[11 22 55 66]
 [33 44 77 88]]


# Questions 6:

In [18]:
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
list1 = [10,20,10,30,40,40,70,80,80,90] 
print("The unique values from 1st list is") 
unique(list1)
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[10 20 30 40 70 80 90]
No of unique items in the list are: 7
